micronaut:
  application:
    name: veiculoService

datasources:
  default:
    url: jdbc:postgresql://127.0.0.1:5433/dbveiculos
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '1234567'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
netty:
  default:
    allocator:
      max-order: 3
